### ISSUE TITLE
App crashes when BCB server is unreachable

### ISSUE THREAD

**Issue by jeroenhd** [jeroenhd/UnofficialBCBReader#44]
When the BCB server goes down, the app crashes. This does not happen when there is no connectivity at all, only if the server is down (due to load perhaps)

```{ 
  "app" : { 
      "appVersion" : 5,
      "appVersionName" : "Elementary master@a839a00 (20170517213156)"
    },
  "crash" : { 
      "exceptionType" : "java.lang.NullPointerException",
      "stacktrace" : "java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
    at nl.jeroenhd.app.bcbreader.activities.ChapterListActivity$2.onErrorResponse(ChapterListActivity.java:81)
    at com.android.volley.Request.deliverError(Request.java:564)
    at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:101)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6186)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)",
      "threadName" : "main"
    },
  "device" : { 
      "androidVersion" : "7.1.2",
      "model" : "A0001"
    },
  "permissions" : [ 
      "android.permission.INTERNET",
      "android.permission.RECEIVE_BOOT_COMPLETED",
      "android.permission.WAKE_LOCK"
    ],
  "reportVersion" : 1
}```

**Comment by jeroenhd** [comment]
This is the same exception as the one in #46. It was fixed by the most recent commit.

Closing these bug reports for now.
